<?php 
    $queries = [
		## USERS 
		"lista_user" => "SELECT DISTINCT usr,P_NOMBRE,P_APELLIDO FROM intradb.users U  INNER JOIN o_m.PERSONAL P ON U.PERSONAL_ID = P.ID WHERE SUBGERENCIA = 'O&M' AND VACACIONES = 'NO' AND U.md5_passw <> '' ORDER BY P_APELLIDO, P_NOMBRE ",
		"lista_area" => "SELECT DISTINCT AREA FROM o_m.PERSONAL WHERE SUBGERENCIA='O&M' ORDER BY AREA ",
		
		## BITACORA 
        "bitacoras" => "SELECT INICIO,FIN,TITULO,PROBLEMA_ID,PLANNED_ID,TAREA_ID,BITACORA.ID,NODO,BITACORA.usr,TIPO,EVENT_TIME,CEASE_TIME,SC_ID,BIT_SEVERITY,OWNER,CSR,BoletaRED,TOT FROM intradb.BITACORA WHERE FIN IS NULL AND TIPO=0 ORDER BY BIT_SEVERITY DESC,INICIO DESC ",
		"problema_bit" => "SELECT TITULO FROM intradb.PROBLEMA WHERE ID=? ",
		"planned_bit" => "SELECT TITULO FROM intradb.PLANNED WHERE ID=? ",
		"tarea_bit" => "SELECT TITULO FROM intradb.TAREA WHERE TAREA.ID=? ",
		"sc_bit" => "SELECT TITULO FROM intradb.SC WHERE ID=?",
		"doc_bit" => "SELECT CONCAT(A.ASOC_ID,' (',(SELECT T.TIPO_NOMBRE FROM intradb.BITACORA_TIPO T WHERE T.TIPO_ID = A.TIPO_ID),')') AS DOC FROM intradb.BITACORA_ASOC A WHERE A.BITACORA_ID = ? ",
		"asig_bit" => "SELECT o_m.SITIOS.SITE_ID, o_m.SITIOS.SITIO FROM intradb.BITACORA_SITIOS LEFT JOIN o_m.SITIOS ON (intradb.BITACORA_SITIOS.ID_SITIO = o_m.SITIOS.SITE_ID) WHERE ID_BITACORA = ? ORDER BY o_m.SITIOS.SITIO ",
		"desc_bit" => "SELECT usr,INGRESO,DESCRIPCION,ID FROM intradb.CONSOLIDADO WHERE BITACORA_ID=? ORDER BY INGRESO ",
		## CREAR BITACORA 
		"severidad_bit" => "SELECT ID,NOMBRE FROM intradb.PID_SEV_LIST ORDER BY ID ",
		"tipo_problema_bit" => "SELECT ID,NOMBRE FROM intradb.BIT_3PP WHERE VAL=1 ORDER BY NOMBRE ",
		"falla_bit" => "SELECT ID,FALLA FROM intradb.BIT_FALLA ORDER BY ID ", 
		"sistema_bit" => "SELECT DISTINCT SISTEMA FROM intradb.BIT_SVA ORDER BY SISTEMA ",
		"plataform_bit" => "SELECT DISTINCT PLATAFORMA FROM intradb.BIT_SVA WHERE SISTEMA=? ORDER BY PLATAFORMA ",
		"servicio_bit" => "SELECT DISTINCT SERVICIO FROM intradb.BIT_SVA WHERE SISTEMA=? AND PLATAFORMA=? ORDER BY SERVICIO ",
		"elemento_bit" => "SELECT DISTINCT ELEMENTO FROM intradb.BIT_SVA WHERE SISTEMA=? AND PLATAFORMA=? AND SERVICIO=? ORDER BY ELEMENTO ",
		## NUEVA BITACORA 
		# OPERSIS 
		"nueva_bit_opersis" => "INSERT INTO intradb.BITACORA (INICIO,TITULO,usr,TIPO,BIT_SEVERITY,NODO,BIT_CLAS,OWNER) VALUES (NOW(),?,?,?,?,?,?,?) ",
		"nueva_bit_opersis2" => "INSERT INTO intradb.BIT_NODO (BIT_ID,NODO) VALUES (?,?) ",
		"nueva_bit_opersis3" => "INSERT INTO intradb.BIT_SERVICIO (BIT_ID,SERVICIO) VALUES (?,?) ",
		"nueva_bit_comment" => "INSERT INTO intradb.CONSOLIDADO (usr,DESCRIPCION,INGRESO,BITACORA_ID) VALUES (?,?,NOW(),? ) ",
		"update_bit" => "UPDATE intradb.BITACORA SET FIN=NOW() WHERE ID=? ",
		"update_bit2" => "UPDATE intradb.BITACORA SET EVENT_TIME=? WHERE ID=? ",
		"update_bit3" => "UPDATE intradb.BITACORA SET CEASE_TIME=? WHERE ID=? ",
		
		## GSM 
		"nueva_bit_opc" => "SELECT ID,OPCION FROM intradb.BIT_OPCIONES ORDER BY OPCION ",
		"nueva_bit_SitNodServ1" => "SELECT SITE_ID,SITIO,NOMBRE FROM o_m.SITIOS WHERE ESTADO IN ('OPERATIVO','OPERATIVO_CON_INTERFERENCIA','INITIAL_TUNNING','HALTED_KPI','HALTED_FALLA') AND SITIO IS NOT NULL AND NOMBRE IS NOT NULL ORDER BY NOMBRE ASC ",
		"nueva_bit_SitNodServ2" => "SELECT DISTINCT SITE_ID,SITIO,NOMBRE as A FROM o_m.SITIOS S JOIN o_m.ACT_ALARM AA ON S.RSITE = AA.EQ WHERE S.ESTADO IN ('OPERATIVO', 'OPERATIVO_CON_INTERFERENCIA', 'INITIAL_TUNNING', 'HALTED_KPI', 'HALTED_FALLA') UNION SELECT RPT_ID,SUBSTRING(NAME, 1, 5),SUBSTRING(NAME, 7) AS A FROM	o_m.ACT_RPT_STAT ORDER BY A ",
		"nueva_bit_ne" => "SELECT NOMBRE FROM intradb.NE ORDER BY NOMBRE ", 
		"nueva_bit_serv" => "SELECT NOMBRE FROM intradb.SERVICIO ORDER BY NOMBRE ",
		"nueva_bit_bitSitio" => "INSERT INTO intradb.BIT_SITIO (BIT_ID,SITIO) VALUES (':id',':value') ",
		"update_bit4" => "UPDATE intradb.BITACORA SET ID_SITIO=':site' WHERE ID=:id ",
			## QUERYS PANELES ALARMAS 
			"select_bit" => "SELECT TITULO, INICIO FROM intradb.BITACORA WHERE ID=:id ",
			"update_2g" => "UPDATE intradb.ACT_ALARM_PANEL_2G_NEW SET ID=:id, TITULO=':titulo', INICIO=':inicio' WHERE SITIO LIKE '%:ss' ",
			"update_3g" => "UPDATE intradb.ACT_ALARM_PANEL_3G_NEW SET ID=:id, TITULO=':titulo', INICIO=':inicio' WHERE SITIO LIKE '%:ss' ",
			"update_4g" => "UPDATE o_m.LTE_ALARM_PANEL SET BIT_ID=:id WHERE SITE LIKE '%:ss' ",
			####################
		"update_bit5" => "UPDATE intradb.BITACORA SET NODO=? WHERE ID=? ",
		"nueva_bit_fallas" => "SELECT A.IDREL as IDREL, A.IDTIPO, A.IDFALLA, B.DESCRIPCION_FALLA, C.DESCRIPCION FROM intradb.REL_TIPOS_FALLAS A INNER JOIN intradb.FALLAS_BITACORA B ON (A.IDFALLA = B.IDFALLA) INNER JOIN intradb.TIPO_FALLAS C ON (C.IDTIPO = A.IDTIPO) WHERE A.IDTIPO=? ORDER BY B.DESCRIPCION_FALLA ASC ",
		"nueva_bit_fallas2" => "SELECT ID_PAIS, PAIS FROM intradb.PAISES ",
		"nueva_bit_fallas3" => "SELECT ID_PAIS, ID_REGION, REGION FROM intradb.REGIONES WHERE ID_PAIS=? ORDER BY REGION ",
		"nueva_bit_fallas4" => "SELECT ID_PAIS, IFNULL(ID_REGION,-1) ID_REGION, IFNULL(ID_ZONA,-1) ID_ZONA, ZONA FROM intradb.ZONA WHERE IFNULL(ID_PAIS,'')=? AND IFNULL(ID_REGION,'')=? ORDER BY ZONA ASC ",
		"nueva_bit_fallas5" => "SELECT Z.ID_PAIS, IFNULL(Z.ID_REGION,-1) ID_REGION, IFNULL(Z.ID_ZONA,-1) ID_ZONA, L.ID_LUGAR , L.LUGAR FROM intradb.LUGAR L INNER JOIN intradb.ZONA Z ON (Z.ID_ZONA = L.ID_ZONA) WHERE Z.ID_ZONA = ? ORDER BY LUGAR ASC ", 
		
		## SEARCH BIT QUERY 
		"search_bit" => "SELECT INICIO,FIN,TITULO,PROBLEMA_ID,PLANNED_ID,TAREA_ID,BITACORA.ID,NODO,BITACORA.usr,TIPO,EVENT_TIME,CEASE_TIME,SC_ID,BIT_SEVERITY,OWNER,CSR,BoletaRED,TOT,INC_PE FROM intradb.BITACORA ? ? ORDER BY INICIO DESC ",
		
		## EDIT_TIME 
		"bit_edit_time1" => "SELECT EXTRACT(YEAR FROM EVENT_TIME) YEAR,EXTRACT(MONTH FROM EVENT_TIME) MONTH,EXTRACT(DAY FROM EVENT_TIME) DAY,EXTRACT(HOUR FROM EVENT_TIME) HOUR,EXTRACT(MINUTE FROM EVENT_TIME) MIN FROM intradb.BITACORA WHERE ID=:bid ",
		"bit_edit_time2" => "SELECT EXTRACT(YEAR FROM CEASE_TIME) YEAR,EXTRACT(MONTH FROM CEASE_TIME) MONTH,EXTRACT(DAY FROM CEASE_TIME) DAY,EXTRACT(HOUR FROM CEASE_TIME) HOUR,EXTRACT(MINUTE FROM CEASE_TIME) MIN FROM intradb.BITACORA WHERE ID=:bid ",
		"bit_update_time1" => "UPDATE intradb.BITACORA SET EVENT_TIME=':time' WHERE ID=:id ",
		"bit_update_time2" => "UPDATE intradb.BITACORA SET CEASE_TIME=':time' WHERE ID=:id ",
		
		## CREAR_ACCION 
		"sel_bitacora" => "SELECT PROBLEMA_ID,PLANNED_ID,TAREA_ID,SC_ID,CSR,BoletaRED,TOT,INC_PE FROM intradb.BITACORA WHERE ID=? ",
		"insert_bit_conso" => "INSERT INTO intradb.CONSOLIDADO (usr,DESCRIPCION,INGRESO,BITACORA_ID,PROBLEMA_ID,PLANNED_ID,TAREA_ID,SC_ID) VALUES (?,?,NOW(),?,?,?,?,?) ",
		"sel_bitacora_asoc" => "SELECT ASOC_ID, TIPO_ID FROM intradb.BITACORA_ASOC WHERE BITACORA_ID = ? ",
		"insert_bit_conso2" => "INSERT INTO intradb.CONSOLIDADO (usr,DESCRIPCION,INGRESO,BITACORA_ID,PROBLEMA_ID,PLANNED_ID,TAREA_ID,SC_ID) VALUES (?,?,NOW(),0,",
		
		## EDIT_BITACORA 
		"edit_bit_op" => "SELECT NOMBRE FROM intradb.BIT_3PP WHERE VAL=1 ORDER BY NOMBRE ",
		"edit_bit_gsm" => "SELECT OPCION FROM intradb.BIT_OPCIONES ORDER BY OPCION ",
		"update_bit_edit" => "UPDATE intradb.BITACORA SET TITULO=':descripcion',BIT_CLAS=':clasificacion' WHERE ID=:id ",
		"update_bit_edit2" => "UPDATE intradb.ACT_ALARM_PANEL_2G_NEW SET TITULO=':descripcion' WHERE ID=:id ",
		"update_bit_edit3" => "UPDATE intradb.ACT_ALARM_PANEL_3G_NEW SET TITULO=':descripcion' WHERE ID=:id ",
		
		## ADD NODO BITACORA 
		"add_nodo_bit" => "SELECT NODO FROM intradb.BITACORA WHERE ID=:id ",
		"del_node_nod" => "DELETE FROM intradb.BIT_NODO WHERE BIT_ID=':id' ",
		"del_node_serv" => "DELETE FROM intradb.BIT_SERVICIO WHERE BIT_ID=':id' ",
		"del_node_sitio" => "DELETE FROM intradb.BIT_SITIO WHERE BIT_ID=':id' ",
		
		## EDIT_SEVERITY 
		"edit_severity" => "SELECT BIT_SEVERITY FROM intradb.BITACORA WHERE ID=:id ",
		"update_severity" => "UPDATE intradb.BITACORA SET BIT_SEVERITY=:severidad,BIT_SEV_WRONG=:mala WHERE ID=:id ",
		
		## CAMBIAR TIPO 
		"update_bit_tipo" => "UPDATE intradb.BITACORA SET TIPO=:tipo WHERE ID=:id ",
		"update_bit_usr" => "UPDATE intradb.BITACORA SET usr=':owner' WHERE ID=:bid ",
		
		## ASOCIAR BITACORA 
		"asoc_bit_btipo" => "SELECT TIPO, DESCRIPCION FROM intradb.BIT_TIPO ORDER BY ID ",
		"update_bit_asoc_pid" => "UPDATE intradb.BITACORA SET PROBLEMA_ID=:var WHERE ID=:id ",
		"update_bit_asoc_tot" => "UPDATE intradb.BITACORA SET TOT=:var WHERE ID=:id ",
		"update_bit_asoc_tp" => "UPDATE intradb.BITACORA SET PLANNED_ID=:var WHERE ID=:id ",
		"update_bit_asoc_sc" => "UPDATE intradb.BITACORA SET SC_ID=:var WHERE ID=:id ",
		"update_bit_asoc_tar" => "UPDATE intradb.BITACORA SET TAREA_ID=:var WHERE ID=:id ",
		"update_bit_asoc_csr" => "UPDATE intradb.BITACORA SET CSR=:var WHERE ID=:id ",
		"update_bit_asoc_incpe" => "UPDATE intradb.BITACORA SET INC_PE=:var WHERE ID=:id ",
		"update_bit_asoc_bred" => "UPDATE intradb.BITACORA SET BoletaRED=:var WHERE ID=:id ",
		"asoc_bit_pid" => "SELECT ID FROM intradb.BITACORA WHERE FIN IS NULL AND PROBLEMA_ID=:assoc_id ",
		"asoc_pid" => "SELECT ID FROM intradb.PROBLEMA WHERE ID=:assoc_id ",
		"asoc_bit_tot" => "SELECT ID FROM intradb.BITACORA WHERE FIN IS NULL AND TOT=:assoc_id ",
		"asoc_bit_tp" => "SELECT ID FROM intradb.BITACORA WHERE FIN IS NULL AND PLANNED_ID=:assoc_id ",
		"asoc_tp" => "SELECT ID FROM intradb.PLANNED WHERE ID=:assoc_id ",
		"asoc_bit_sc" => "SELECT ID FROM intradb.BITACORA WHERE FIN IS NULL AND SC_ID=:assoc_id ",
		"asoc_sc" => "SELECT ID FROM intradb.SC WHERE ID=:assoc_id ",
		"asoc_bit_tar" => "SELECT ID FROM intradb.BITACORA WHERE FIN IS NULL AND TAREA_ID=:assoc_id ",
		"asoc_tar" => "SELECT ID FROM TAREA WHERE ID=:assoc_id ",
		"asoc_bit_csr" => "SELECT ID FROM intradb.BITACORA WHERE FIN IS NULL AND CSR=:assoc_id ",
		"asoc_bit_incpe" => "SELECT ID FROM intradb.BITACORA WHERE FIN IS NULL AND INC_PE=:assoc_id ",
		"asoc_bit_bred" => "SELECT ID FROM intradb.BITACORA WHERE FIN IS NULL AND BoletaRED=:assoc_id ",
		
		## DOCUMENTAR_TP
		"doc_bit_tipo" => "SELECT TIPO_ID,TIPO_NOMBRE FROM intradb.BITACORA_TIPO ORDER BY TIPO_ID ",
		"doc_bit_asoc" => "SELECT * FROM intradb.BITACORA_ASOC WHERE BITACORA_ID = :id_bitacora AND ASOC_ID = :txt_tarea AND TIPO_ID = :id_tipo ",
		"ins_bit_asoc" => "INSERT INTO intradb.BITACORA_ASOC (BITACORA_ID, ASOC_ID, TIPO_ID) VALUES (:id_bitacora, :txt_tarea, :id_tipo) ",
		"ins_conso_bit_asoc" => "INSERT INTO intradb.CONSOLIDADO (DESCRIPCION, usr, INGRESO, PROBLEMA_ID, PLANNED_ID, TAREA_ID, BITACORA_ID, SC_ID) SELECT DESCRIPCION,usr,NOW(),:pid,:txt_tarea,:tar,:bitacora,:sc FROM intradb.CONSOLIDADO WHERE BITACORA_ID=:id_bitacora ",
		"doc_bit_asoc_tip" => "SELECT BA.ASOC_ID,BT.TIPO_NOMBRE FROM intradb.BITACORA_ASOC BA INNER JOIN intradb.BITACORA_TIPO BT ON BA.TIPO_ID = BT.TIPO_ID WHERE BITACORA_ID = :id_bitacora ",
		
		## ASOCIAR SITIOS 
		"ins_bit_sitios" => "INSERT INTO intradb.BITACORA_SITIOS (ID_BITACORA, ID_SITIO) VALUES (':bitacora',':sitios') ",
		"del_bit_sitios" => "DELETE FROM intradb.BITACORA_SITIOS WHERE ID_BITACORA = ':bitacora' AND ID_SITIO = ':sitios' ",
		"asoc_sitios_bit" => "SELECT SITE_ID, SITIO FROM o_m.SITIOS WHERE ESTADO IN ('OPERATIVO','OPERATIVO_CON_INTERFERENCIA','INITIAL_TUNNING','HALTED_KPI','HALTED_FALLA','INTEGRADO') AND SITE_ID NOT IN (SELECT DISTINCT ID_SITIO FROM intradb.BITACORA_SITIOS WHERE ID_BITACORA = ':bitacora') ORDER BY SITIO ", 
		"asoc_bit_sitios" => "SELECT S.SITE_ID, S.SITIO FROM intradb.BITACORA_SITIOS BS LEFT JOIN o_m.SITIOS S ON (BS.ID_SITIO = S.SITE_ID) WHERE ID_BITACORA = ':bitacora' ORDER BY S.SITIO ", 
		
		## BITACORA_DE 
		"sel_mi_bit" => "SELECT INICIO,FIN,TITULO,PROBLEMA_ID,PLANNED_ID,TAREA_ID,ID,NODO,usr,TIPO,EVENT_TIME,CEASE_TIME,SC_ID,BIT_SEVERITY,OWNER FROM intradb.BITACORA WHERE FIN IS NULL AND usr=? ORDER BY BIT_SEVERITY DESC,INICIO DESC ",
		
		## BITACORA_SEV 
		"sel_bit_sev" => "SELECT INICIO,FIN,TITULO,PROBLEMA_ID,PLANNED_ID,TAREA_ID,ID,NODO,usr,TIPO,EVENT_TIME,CEASE_TIME,SC_ID,BIT_SEVERITY,OWNER FROM BITACORA WHERE FIN IS NULL AND BIT_SEVERITY >= ? ORDER BY BIT_SEVERITY desc,INICIO desc ", 
		
		"sel_bit_grupo" => "SELECT INICIO,FIN,TITULO,PROBLEMA_ID,PLANNED_ID,TAREA_ID,B.ID,NODO,B.usr,TIPO,EVENT_TIME,CEASE_TIME,SC_ID,BIT_SEVERITY,OWNER FROM intradb.BITACORA B INNER JOIN intradb.users U ON B.usr=U.usr INNER JOIN o_m.PERSONAL P ON U.personal_id =P.ID WHERE FIN IS NULL AND P.AREA=? ORDER BY BIT_SEVERITY DESC,INICIO DESC ",
		
		"sel_bit_scroll" => "SELECT INICIO,FIN,TITULO,PROBLEMA_ID,PLANNED_ID,TAREA_ID,ID,NODO,usr,TIPO,EVENT_TIME,CEASE_TIME,SC_ID,BIT_SEVERITY,OWNER FROM intradb.BITACORA ORDER BY INICIO DESC LIMIT ?,? ",
		"sel_log_scroll" => "SELECT usr,INGRESO,DESCRIPCION,PROBLEMA_ID,PLANNED_ID,TAREA_ID,BITACORA_ID,SC_ID FROM intradb.CONSOLIDADO ORDER BY INGRESO DESC LIMIT :offset,:nr_records ",
		
		"sel_sitio_bit" => "SELECT SITE_ID,SITIO,NOMBRE FROM o_m.SITIOS WHERE SITIO IS NOT NULL AND NOMBRE IS NOT NULL ORDER BY SITIO ",
		"sel_sitios_bit" => "SELECT A.ASOC_ID, A.TIPO_ID, (SELECT T.TIPO_NOMBRE FROM intradb.BITACORA_TIPO T WHERE T.TIPO_ID = A.TIPO_ID) TIPO_NOMBRE FROM intradb.BITACORA_ASOC A, intradb.BITACORA_SITIOS S WHERE A.BITACORA_ID = S.ID_BITACORA AND S.ID_SITIO = ':sitio' ",
		
		"log_sel_conso" => "SELECT usr,INGRESO,DESCRIPCION,PROBLEMA_ID,PLANNED_ID,TAREA_ID,BITACORA_ID,SC_ID FROM intradb.CONSOLIDADO WHERE INGRESO > SUBDATE(NOW(),INTERVAL 2 HOUR) ORDER BY INGRESO DESC LIMIT 0,10 ", 
		
		"sel_bit" => "SELECT TITULO,NODO FROM intradb.BITACORA WHERE ID=:id ",
		
		"sel_conso_search" => "SELECT usr,INGRESO,DESCRIPCION,PROBLEMA_ID,PLANNED_ID,TAREA_ID,BITACORA_ID,SC_ID FROM intradb.CONSOLIDADO :clauses ORDER BY INGRESO DESC ",
		
		"sel_bcon_search" => "SELECT TIPO,ID,TITULO,DESCRIPCION,MATCH(TITULO,DESCRIPCION,SUMMARY) AGAINST (':descripcion' :clauses) AS Score FROM intradb.BCON WHERE MATCH (TITULO,DESCRIPCION,SUMMARY) AGAINST (':descripcion' :clauses) ORDER BY Score DESC LIMIT 0,200 ",
		
		## ADM SISTEMAS 
		"ins_tbl_adm" => "INSERT INTO :table (NOMBRE) VALUES ('**********') ",
		"sel_tbl_adm" => "SELECT ID,NOMBRE FROM :table ORDER BY NOMBRE ",
		"sel_bit_adm" => "SELECT NOMBRE FROM :table WHERE ID=:id ",
		"del_bit_adm" => "DELETE FROM :table WHERE ID=:id ",
		"upd_bit_adm" => "UPDATE :table SET NOMBRE=':nuevo' WHERE ID=:id ",
		
    ];